spring:
  datasource:
    dynamic:
      primary:
          mysql
      datasource:
        mysql:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/flight_booking?serverTimezone=America/Vancouver&characterEncoding=utf-8
          username: root
          password: 123456
      druid:
        initial-size: 10
        max-active: 100
        min-idle: 10
        max-wait: 60000
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        stat-view-servlet:
          enabled: true
          url-pattern: /druid/*123
        filter:
          stat:
            log-slow-sql: true
            slow-sql-millis: 1000
            merge-sql: false
          wall:
            config:
              multi-statement-allow: true
  data:
    redis:
      host: 127.0.0.1
      port: 6379


logging:
  file:
    path: ./logs
    max-history: 30
    max-size: 20MB

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


springdoc:
  components:
    securitySchemes:
      usernameHeader:
        type: apiKey
        in: header
        name: X-Username
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true



system:
  config:
    auth:
      tokenKey: "apiToken"
      tokenSignSecret: "flight  booking"
      tokenExpiredTime: 360000000
      excludeUrls: "/**"

openai:
  api:
    key: